version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    command: flower --broker=redis://redis:6379/0
    depends_on:
      - redis